name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: govinda777
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Clone repo to keep generated files
      - name: Checkout repo
        uses: actions/checkout@v4

      # Generate 3D Contribution Graph
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # Move 3D output into dist folder for GitHub Pages
      - name: Move 3D output to dist
        run: |
          mkdir -p dist/profile-3d-contrib
          cp -r profile-3d-contrib/* dist/profile-3d-contrib/

      # Deploy both snake and 3d graph via GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
